//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test17
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказы.
    /// </summary>
    // *** Start programmer edit section *** (Заказы CustomAttributes)

    // *** End programmer edit section *** (Заказы CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаказыE", new string[] {
            "КодЗаказа as \'Код заказа\'",
            "Статус as \'Статус\'",
            "Дата as \'Дата\'",
            "Контрагент as \'Контрагент\'",
            "Контрагент.Фамилия as \'Фамилия\'",
            "Продавец as \'Продавец\'",
            "Продавец.Фамилия as \'Фамилия\'"}, Hidden=new string[] {
            "Контрагент.Фамилия",
            "Продавец.Фамилия"})]
    [AssociatedDetailViewAttribute("ЗаказыE", "СоставЗаказа", "СоставЗаказаE", true, "", "Состав заказа", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ЗаказыE", "Контрагент", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [MasterViewDefineAttribute("ЗаказыE", "Продавец", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [View("ЗаказыL", new string[] {
            "КодЗаказа as \'Код заказа\'",
            "Статус as \'Статус\'",
            "Дата as \'Дата\'",
            "Контрагент.Фамилия as \'Фамилия\'",
            "Продавец.Фамилия as \'Фамилия\'"})]
    public class Заказы : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодЗаказа;
        
        private IIS.Test17.Статусы fСтатус;
        
        private System.DateTime fДата;
        
        private IIS.Test17.Контрагент fКонтрагент;
        
        private IIS.Test17.Продавец fПродавец;
        
        private IIS.Test17.DetailArrayOfСоставЗаказа fСоставЗаказа;
        
        // *** Start programmer edit section *** (Заказы CustomMembers)

        // *** End programmer edit section *** (Заказы CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.Дата CustomAttributes)

        // *** End programmer edit section *** (Заказы.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.Дата Get start)

                // *** End programmer edit section *** (Заказы.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Заказы.Дата Get end)

                // *** End programmer edit section *** (Заказы.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.Дата Set start)

                // *** End programmer edit section *** (Заказы.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Заказы.Дата Set end)

                // *** End programmer edit section *** (Заказы.Дата Set end)
            }
        }
        
        /// <summary>
        /// КодЗаказа.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.КодЗаказа CustomAttributes)

        // *** End programmer edit section *** (Заказы.КодЗаказа CustomAttributes)
        public virtual int КодЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.КодЗаказа Get start)

                // *** End programmer edit section *** (Заказы.КодЗаказа Get start)
                int result = this.fКодЗаказа;
                // *** Start programmer edit section *** (Заказы.КодЗаказа Get end)

                // *** End programmer edit section *** (Заказы.КодЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.КодЗаказа Set start)

                // *** End programmer edit section *** (Заказы.КодЗаказа Set start)
                this.fКодЗаказа = value;
                // *** Start programmer edit section *** (Заказы.КодЗаказа Set end)

                // *** End programmer edit section *** (Заказы.КодЗаказа Set end)
            }
        }
        
        /// <summary>
        /// Статус.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.Статус CustomAttributes)

        // *** End programmer edit section *** (Заказы.Статус CustomAttributes)
        public virtual IIS.Test17.Статусы Статус
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.Статус Get start)

                // *** End programmer edit section *** (Заказы.Статус Get start)
                IIS.Test17.Статусы result = this.fСтатус;
                // *** Start programmer edit section *** (Заказы.Статус Get end)

                // *** End programmer edit section *** (Заказы.Статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.Статус Set start)

                // *** End programmer edit section *** (Заказы.Статус Set start)
                this.fСтатус = value;
                // *** Start programmer edit section *** (Заказы.Статус Set end)

                // *** End programmer edit section *** (Заказы.Статус Set end)
            }
        }
        
        /// <summary>
        /// Заказы.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.Контрагент CustomAttributes)

        // *** End programmer edit section *** (Заказы.Контрагент CustomAttributes)
        [PropertyStorage(new string[] {
                "Контрагент"})]
        [NotNull()]
        public virtual IIS.Test17.Контрагент Контрагент
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.Контрагент Get start)

                // *** End programmer edit section *** (Заказы.Контрагент Get start)
                IIS.Test17.Контрагент result = this.fКонтрагент;
                // *** Start programmer edit section *** (Заказы.Контрагент Get end)

                // *** End programmer edit section *** (Заказы.Контрагент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.Контрагент Set start)

                // *** End programmer edit section *** (Заказы.Контрагент Set start)
                this.fКонтрагент = value;
                // *** Start programmer edit section *** (Заказы.Контрагент Set end)

                // *** End programmer edit section *** (Заказы.Контрагент Set end)
            }
        }
        
        /// <summary>
        /// Заказы.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.Продавец CustomAttributes)

        // *** End programmer edit section *** (Заказы.Продавец CustomAttributes)
        [PropertyStorage(new string[] {
                "Продавец"})]
        [NotNull()]
        public virtual IIS.Test17.Продавец Продавец
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.Продавец Get start)

                // *** End programmer edit section *** (Заказы.Продавец Get start)
                IIS.Test17.Продавец result = this.fПродавец;
                // *** Start programmer edit section *** (Заказы.Продавец Get end)

                // *** End programmer edit section *** (Заказы.Продавец Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.Продавец Set start)

                // *** End programmer edit section *** (Заказы.Продавец Set start)
                this.fПродавец = value;
                // *** Start programmer edit section *** (Заказы.Продавец Set end)

                // *** End programmer edit section *** (Заказы.Продавец Set end)
            }
        }
        
        /// <summary>
        /// Заказы.
        /// </summary>
        // *** Start programmer edit section *** (Заказы.СоставЗаказа CustomAttributes)

        // *** End programmer edit section *** (Заказы.СоставЗаказа CustomAttributes)
        public virtual IIS.Test17.DetailArrayOfСоставЗаказа СоставЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (Заказы.СоставЗаказа Get start)

                // *** End programmer edit section *** (Заказы.СоставЗаказа Get start)
                if ((this.fСоставЗаказа == null))
                {
                    this.fСоставЗаказа = new IIS.Test17.DetailArrayOfСоставЗаказа(this);
                }
                IIS.Test17.DetailArrayOfСоставЗаказа result = this.fСоставЗаказа;
                // *** Start programmer edit section *** (Заказы.СоставЗаказа Get end)

                // *** End programmer edit section *** (Заказы.СоставЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказы.СоставЗаказа Set start)

                // *** End programmer edit section *** (Заказы.СоставЗаказа Set start)
                this.fСоставЗаказа = value;
                // *** Start programmer edit section *** (Заказы.СоставЗаказа Set end)

                // *** End programmer edit section *** (Заказы.СоставЗаказа Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаказыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказыE", typeof(IIS.Test17.Заказы));
                }
            }
            
            /// <summary>
            /// "ЗаказыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказыL", typeof(IIS.Test17.Заказы));
                }
            }
        }
    }
}
