//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test17
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Место выдачи.
    /// </summary>
    // *** Start programmer edit section *** (МестоВыдачи CustomAttributes)

    // *** End programmer edit section *** (МестоВыдачи CustomAttributes)
    [AutoAltered()]
    [Caption("Место выдачи")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("МестоВыдачиE", new string[] {
            "Адрес as \'Адрес\'"})]
    [View("МестоВыдачиL", new string[] {
            "Адрес as \'Адрес\'"})]
    public class МестоВыдачи : ICSSoft.STORMNET.DataObject
    {
        
        private string fАдрес;
        
        // *** Start programmer edit section *** (МестоВыдачи CustomMembers)

        // *** End programmer edit section *** (МестоВыдачи CustomMembers)

        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (МестоВыдачи.Адрес CustomAttributes)

        // *** End programmer edit section *** (МестоВыдачи.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (МестоВыдачи.Адрес Get start)

                // *** End programmer edit section *** (МестоВыдачи.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (МестоВыдачи.Адрес Get end)

                // *** End programmer edit section *** (МестоВыдачи.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (МестоВыдачи.Адрес Set start)

                // *** End programmer edit section *** (МестоВыдачи.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (МестоВыдачи.Адрес Set end)

                // *** End programmer edit section *** (МестоВыдачи.Адрес Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "МестоВыдачиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МестоВыдачиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МестоВыдачиE", typeof(IIS.Test17.МестоВыдачи));
                }
            }
            
            /// <summary>
            /// "МестоВыдачиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МестоВыдачиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МестоВыдачиL", typeof(IIS.Test17.МестоВыдачи));
                }
            }
        }
    }
}
