//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test17
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Оповещения.
    /// </summary>
    // *** Start programmer edit section *** (Оповещения CustomAttributes)

    // *** End programmer edit section *** (Оповещения CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОповещенияE", new string[] {
            "Описание as \'Описание\'",
            "МестоВыдачи as \'Место выдачи\'",
            "МестоВыдачи.Адрес as \'Адрес\'",
            "Заказы as \'Заказы\'",
            "Заказы.КодЗаказа as \'Код заказа\'"}, Hidden=new string[] {
            "МестоВыдачи.Адрес",
            "Заказы.КодЗаказа"})]
    [MasterViewDefineAttribute("ОповещенияE", "МестоВыдачи", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Адрес")]
    [MasterViewDefineAttribute("ОповещенияE", "Заказы", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "КодЗаказа")]
    [View("ОповещенияL", new string[] {
            "Описание as \'Описание\'",
            "МестоВыдачи.Адрес as \'Адрес\'",
            "Заказы.КодЗаказа as \'Код заказа\'"})]
    public class Оповещения : ICSSoft.STORMNET.DataObject
    {
        
        private string fОписание;
        
        private IIS.Test17.МестоВыдачи fМестоВыдачи;
        
        private IIS.Test17.Заказы fЗаказы;
        
        // *** Start programmer edit section *** (Оповещения CustomMembers)

        // *** End programmer edit section *** (Оповещения CustomMembers)

        
        /// <summary>
        /// Описание.
        /// </summary>
        // *** Start programmer edit section *** (Оповещения.Описание CustomAttributes)

        // *** End programmer edit section *** (Оповещения.Описание CustomAttributes)
        [StrLen(255)]
        public virtual string Описание
        {
            get
            {
                // *** Start programmer edit section *** (Оповещения.Описание Get start)

                // *** End programmer edit section *** (Оповещения.Описание Get start)
                string result = this.fОписание;
                // *** Start programmer edit section *** (Оповещения.Описание Get end)

                // *** End programmer edit section *** (Оповещения.Описание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оповещения.Описание Set start)

                // *** End programmer edit section *** (Оповещения.Описание Set start)
                this.fОписание = value;
                // *** Start programmer edit section *** (Оповещения.Описание Set end)

                // *** End programmer edit section *** (Оповещения.Описание Set end)
            }
        }
        
        /// <summary>
        /// Оповещения.
        /// </summary>
        // *** Start programmer edit section *** (Оповещения.Заказы CustomAttributes)

        // *** End programmer edit section *** (Оповещения.Заказы CustomAttributes)
        [PropertyStorage(new string[] {
                "Заказы"})]
        [NotNull()]
        public virtual IIS.Test17.Заказы Заказы
        {
            get
            {
                // *** Start programmer edit section *** (Оповещения.Заказы Get start)

                // *** End programmer edit section *** (Оповещения.Заказы Get start)
                IIS.Test17.Заказы result = this.fЗаказы;
                // *** Start programmer edit section *** (Оповещения.Заказы Get end)

                // *** End programmer edit section *** (Оповещения.Заказы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оповещения.Заказы Set start)

                // *** End programmer edit section *** (Оповещения.Заказы Set start)
                this.fЗаказы = value;
                // *** Start programmer edit section *** (Оповещения.Заказы Set end)

                // *** End programmer edit section *** (Оповещения.Заказы Set end)
            }
        }
        
        /// <summary>
        /// Оповещения.
        /// </summary>
        // *** Start programmer edit section *** (Оповещения.МестоВыдачи CustomAttributes)

        // *** End programmer edit section *** (Оповещения.МестоВыдачи CustomAttributes)
        [PropertyStorage(new string[] {
                "МестоВыдачи"})]
        [NotNull()]
        public virtual IIS.Test17.МестоВыдачи МестоВыдачи
        {
            get
            {
                // *** Start programmer edit section *** (Оповещения.МестоВыдачи Get start)

                // *** End programmer edit section *** (Оповещения.МестоВыдачи Get start)
                IIS.Test17.МестоВыдачи result = this.fМестоВыдачи;
                // *** Start programmer edit section *** (Оповещения.МестоВыдачи Get end)

                // *** End programmer edit section *** (Оповещения.МестоВыдачи Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оповещения.МестоВыдачи Set start)

                // *** End programmer edit section *** (Оповещения.МестоВыдачи Set start)
                this.fМестоВыдачи = value;
                // *** Start programmer edit section *** (Оповещения.МестоВыдачи Set end)

                // *** End programmer edit section *** (Оповещения.МестоВыдачи Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОповещенияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОповещенияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОповещенияE", typeof(IIS.Test17.Оповещения));
                }
            }
            
            /// <summary>
            /// "ОповещенияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОповещенияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОповещенияL", typeof(IIS.Test17.Оповещения));
                }
            }
        }
    }
}
