//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test17
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Продавец.
    /// </summary>
    // *** Start programmer edit section *** (Продавец CustomAttributes)

    // *** End programmer edit section *** (Продавец CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПродавецE", new string[] {
            "КодПродавца as \'Код продавца\'",
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'"})]
    [View("ПродавецL", new string[] {
            "КодПродавца as \'Код продавца\'",
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'"})]
    public class Продавец : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодПродавца;
        
        private string fФамилия;
        
        private string fИмя;
        
        private string fОтчество;
        
        // *** Start programmer edit section *** (Продавец CustomMembers)

        // *** End programmer edit section *** (Продавец CustomMembers)

        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (Продавец.Имя CustomAttributes)

        // *** End programmer edit section *** (Продавец.Имя CustomAttributes)
        [StrLen(255)]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (Продавец.Имя Get start)

                // *** End programmer edit section *** (Продавец.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (Продавец.Имя Get end)

                // *** End programmer edit section *** (Продавец.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Продавец.Имя Set start)

                // *** End programmer edit section *** (Продавец.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (Продавец.Имя Set end)

                // *** End programmer edit section *** (Продавец.Имя Set end)
            }
        }
        
        /// <summary>
        /// КодПродавца.
        /// </summary>
        // *** Start programmer edit section *** (Продавец.КодПродавца CustomAttributes)

        // *** End programmer edit section *** (Продавец.КодПродавца CustomAttributes)
        public virtual int КодПродавца
        {
            get
            {
                // *** Start programmer edit section *** (Продавец.КодПродавца Get start)

                // *** End programmer edit section *** (Продавец.КодПродавца Get start)
                int result = this.fКодПродавца;
                // *** Start programmer edit section *** (Продавец.КодПродавца Get end)

                // *** End programmer edit section *** (Продавец.КодПродавца Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Продавец.КодПродавца Set start)

                // *** End programmer edit section *** (Продавец.КодПродавца Set start)
                this.fКодПродавца = value;
                // *** Start programmer edit section *** (Продавец.КодПродавца Set end)

                // *** End programmer edit section *** (Продавец.КодПродавца Set end)
            }
        }
        
        /// <summary>
        /// Отчество.
        /// </summary>
        // *** Start programmer edit section *** (Продавец.Отчество CustomAttributes)

        // *** End programmer edit section *** (Продавец.Отчество CustomAttributes)
        [StrLen(255)]
        public virtual string Отчество
        {
            get
            {
                // *** Start programmer edit section *** (Продавец.Отчество Get start)

                // *** End programmer edit section *** (Продавец.Отчество Get start)
                string result = this.fОтчество;
                // *** Start programmer edit section *** (Продавец.Отчество Get end)

                // *** End programmer edit section *** (Продавец.Отчество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Продавец.Отчество Set start)

                // *** End programmer edit section *** (Продавец.Отчество Set start)
                this.fОтчество = value;
                // *** Start programmer edit section *** (Продавец.Отчество Set end)

                // *** End programmer edit section *** (Продавец.Отчество Set end)
            }
        }
        
        /// <summary>
        /// Фамилия.
        /// </summary>
        // *** Start programmer edit section *** (Продавец.Фамилия CustomAttributes)

        // *** End programmer edit section *** (Продавец.Фамилия CustomAttributes)
        [StrLen(255)]
        public virtual string Фамилия
        {
            get
            {
                // *** Start programmer edit section *** (Продавец.Фамилия Get start)

                // *** End programmer edit section *** (Продавец.Фамилия Get start)
                string result = this.fФамилия;
                // *** Start programmer edit section *** (Продавец.Фамилия Get end)

                // *** End programmer edit section *** (Продавец.Фамилия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Продавец.Фамилия Set start)

                // *** End programmer edit section *** (Продавец.Фамилия Set start)
                this.fФамилия = value;
                // *** Start programmer edit section *** (Продавец.Фамилия Set end)

                // *** End programmer edit section *** (Продавец.Фамилия Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПродавецE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПродавецE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПродавецE", typeof(IIS.Test17.Продавец));
                }
            }
            
            /// <summary>
            /// "ПродавецL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПродавецL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПродавецL", typeof(IIS.Test17.Продавец));
                }
            }
        }
    }
}
