//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test17
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Статусы.
    /// </summary>
    // *** Start programmer edit section *** (Статусы CustomAttributes)

    // *** End programmer edit section *** (Статусы CustomAttributes)
    public enum Статусы
    {
        
        // *** Start programmer edit section *** (Статусы.Готов CustomAttributes)

        // *** End programmer edit section *** (Статусы.Готов CustomAttributes)
        Готов,
        
        // *** Start programmer edit section *** (Статусы.Выдан CustomAttributes)

        // *** End programmer edit section *** (Статусы.Выдан CustomAttributes)
        Выдан,
        
        // *** Start programmer edit section *** (Статусы.НаСборке CustomAttributes)

        // *** End programmer edit section *** (Статусы.НаСборке CustomAttributes)
        НаСборке,
    }
}
